### ISSUE TITLE
Ending an observation only rejects first incoming notification

### ISSUE THREAD

**Issue by cburger-scheidlin** [jvermillard/leshan#30]
I have been playing with the observation feature.
As I understand it, ending an observation causes leshan to send a RST message for an incoming notification. However, this is only done for the _first_ incoming notification that is received after the observation is cancelled.

As far as I read the CoAP RFC, this is definitely conforming to the standard, since if leshan receives a NON message that it cannot process, it is not required to send a RST message.

However, this could lead to problems when a lwm2m device sends NON notifications for a long period of time and the RST message is lost. Then we get a situation where the device does not know that the server is no longer interested in the communication.

Therefore I would suggest sending out a RST message for unknown NON messages as well.

**Comment by mkovatsc** [comment]
Just found this here. Yes, the removal of the GitHub Issues section came quite as a suprise to use (officially it should never have been enabled, but Eclipse is working on a policy change AFAIK).
I will look into the RSTs.

**Comment by sbernard31** [comment]
It should be fixed now we use the 1.0.0-M3 which fixes this problem.
(Thx Matthias)
